# Generated by Django 4.2.6 on 2023-10-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIHandler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storestatus',
            name='store_id',
            field=models.IntegerField(),
        ),
    ]
