# Generated by Django 4.2.6 on 2023-10-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIHandler', '0002_alter_storestatus_store_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('store_id', models.IntegerField()),
                ('timestamp_utc', models.DateTimeField()),
                ('uptime_last_hour', models.IntegerField()),
                ('uptime_last_day', models.IntegerField()),
                ('downtime_last_hour', models.IntegerField()),
                ('downtime_last_day', models.IntegerField()),
                ('update_last_week', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='storehours',
            name='id',
        ),
        migrations.RemoveField(
            model_name='storestatus',
            name='id',
        ),
        migrations.RemoveField(
            model_name='storetimezone',
            name='id',
        ),
        migrations.AlterField(
            model_name='storehours',
            name='store_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='storestatus',
            name='store_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='storetimezone',
            name='store_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
