# Generated by Django 4.2.6 on 2023-10-18 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIHandler', '0004_businesshour_businesshourutcm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BusinessHourUTCm',
            new_name='BusinessHourUTC',
        ),
    ]
